module.exports.setPrebidConfig = async (payload, cdnpath, creative, amazonData) => {

    const {
        name,
        configname,
        width,
        height,
        domain,
        passbacktag,
        PREBID_TIMEOUT,
        settings,
        floorPrice,
        cmp,
        cmpTimeout,
        cmpType,
        customCode,
        userId,
        siteId,
        adUnitCode,
        createdBy,
        updatedBy,
        setDomain,
        analytics,
        analyticsEnable,
        analyticsOptions,
        currency,
        // server,
        marketplace,
        marketplaceSettings,
        mainAdapters,
        mainSettings,
        schain,
        schainObject,
        dev,
        adExId,
        logo,
        thirdPartyCMP
    } = payload;
    const {amazon, amazonID, amazonAdUnitCode} = amazonData;

    return {
        cdnpath,
        name,
        configname,
        size: {
            width,
            height
        },
        domain,
        passbacktag,
        creative,
        PREBID_TIMEOUT,
        settings,
        floorPrice,
        amazon,
        amazonID,
        amazonAdUnitCode,
        cmp,
        cmpTimeout,
        cmpType,
        customCode,
        userId,
        siteId,
        adUnitCode,
        createdBy,
        updatedBy,
        setDomain,
        analytics,
        analyticsEnable,
        analyticsOptions,
        currency,
        // server,
        marketplace,
        marketplaceSettings,
        mainAdapters,
        mainSettings,
        schain,
        schainObject,
        dev,
        adExId,
        logo,
        thirdPartyCMP
    }
};
